### ISSUE TITLE
how to start the app?

### ISSUE THREAD

**Issue by Abdelkrim** [ThorstenHans/electron-angular-es6#2]
@ThorstenHans how do we start the electron app after having unzipped the file? 

Could you update the readme accordingly?

**Comment by ofi** [comment]
It's funny I was struggling with this issue quite at the same time. :-)
The problem is the contradiction in the readme vs. the Gulpfile.js vs. index.js, and I have cut the knot like this:
- Correct browser/config.js as depcited in the accompanying article.
- Copy the contents of app/renderer into app/browser
- Change target "copy:app" in Gulpfile.js to copy from 'browser/**/*' instead of 'renderer/**/*' in the gulp.src() call. Then after the next gulp run and extraction of the zip the app starts as intended.

Alternatively you could take the choice the other way round, i. e. set up jspm to live in app/renderer.
I hope these hints may help, but I will fork anyway to tailor the template to my needs, e. g. without the crash reporter which is an interesting plus but of minimal use for my case.

Nevertheless and not least I like to thank Thorsten for this groundwork, especially his blog post, which both have led me to the right direction.

Cheers [ofi]

**Comment by Abdelkrim** [comment]
@ofi could you apply those changes directly into the code? To be honest I hoped to have a quick view on the work of @ThorstenHans and nothing more. 

Thank you for your time, I'll perform the tasks if I really want to see the result.

**Comment by ofi** [comment]
Meanwhile I have forked the repo which you can find under the same name in my account. Maybe this will give you a faster headstart like you initially expected. Good luck!

**Comment by ThorstenHans** [comment]
@ofi send a pull req. The root cause is JSPM their folder management just sucks.

**Comment by ofi** [comment]
Ok, this will happen within two days, as soon as I get back to my home machine.

**Comment by ThorstenHans** [comment]
:+1:

**Comment by Abdelkrim** [comment]
Thanks Dude!
